name: Fetch Tomachi Emojis

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  fetch-emojis:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Setup node env
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      working-directory: ./.github/scripts/fetch-tomachi-emojis/
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node_modules
      uses: actions/cache@v2.1.7
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      working-directory: ./.github/scripts/fetch-tomachi-emojis/
      run: yarn

    - name: Generate README file
      working-directory: ./.github/scripts/fetch-tomachi-emojis/
      run: yarn build --output ../../../icons/

    - name: Commit & Push
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git status | grep modified && git add -A && git commit -v -m "feat: Fetched emojis from Tomachi Emojis [skip ci]" || true
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
