name: Generate readme

on:
  workflow_dispatch:
  push:
    branches:
     - master

jobs:
  generate:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Setup node env
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 16

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      working-directory: ./.github/scripts/generate-readme/
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Cache node_modules
      uses: actions/cache@v3.0.11
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      working-directory: ./.github/scripts/generate-readme/
      run: yarn

    - name: Generate README file
      working-directory: ./.github/scripts/generate-readme/
      run: yarn build --target ../../../icons/ --output ../../../README.md --target-guilds ../../../targetGuilds.json --emojis ../../../emojis.json

    - name: Commit & Push
      run: |
        git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git status | grep modified && git add -A && git commit -v -m "feat: Updated README.md [skip ci]" || true
        git push origin HEAD:${GITHUB_REF};
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
