name: Generate readme

on:
  workflow_dispatch:
  push:
    branches:
     - master

jobs:
  generate:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: ./.github/scripts/generate-readme/.node-version

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        run_install: false
        package_json_file: ./.github/scripts/generate-readme/package.json

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      working-directory: ./.github/scripts/generate-readme/
      run: |
        pnpm install --frozen-lockfile --prefer-frozen-lockfile

    - name: Generate README file
      working-directory: ./.github/scripts/generate-readme/
      run: pnpm start --target-emojis ../../../icons/ --target-stickers ../../../stickers/ --output ../../../README.md --target-guilds ../../../targetGuilds.json --emojis ../../../emojis.json --stickers ../../../stickers.json

    - name: Commit & Push
      run: |
        git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git status | grep modified && git add -A && git commit -v -m "feat: Updated README.md [skip ci]" || true
        git push origin HEAD:${GITHUB_REF};
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
